import type { Property, Amenity } from "@/lib/types";
import { Armchair, Bath, BedDouble, Car, Dumbbell, PawPrint, Waves, Trees, UtensilsCrossed, Wifi, Wind } from "lucide-react";

export const properties: Property[] = [
  {
    id: "p1",
    title: "Modern Family Home in Suburbia",
    description: "A beautiful and spacious modern home perfect for families, located in a quiet suburban neighborhood with great schools and parks nearby.",
    status: "For Sale",
    type: "House",
    location: "Maple Creek, New York",
    price: 750000,
    bedrooms: 4,
    bathrooms: 3,
    size: 2500,
    amenities: ["Pool", "Garage", "Garden", "Air Conditioning"],
    images: ["property-1-ext", "property-1-int-1", "property-1-int-2"],
    agent: { name: "Jane Doe", avatar: "agent-1" },
    featured: true,
  },
  {
    id: "p2",
    title: "Luxury Downtown Apartment",
    description: "Stunning luxury apartment in the heart of the city with breathtaking views, concierge service, and state-of-the-art facilities.",
    status: "For Rent",
    type: "Apartment",
    location: "Central City, San Francisco",
    price: 4500,
    bedrooms: 2,
    bathrooms: 2,
    size: 1200,
    amenities: ["Gym", "Pool", "Concierge", "Parking"],
    images: ["property-2-ext", "property-2-int-1", "property-2-int-2"],
    agent: { name: "John Smith", avatar: "agent-2" },
    featured: true,
  },
  {
    id: "p3",
    title: "Cozy Condo near the Park",
    description: "A charming and cozy condo perfect for young professionals or couples. Located next to a beautiful city park and close to public transport.",
    status: "For Sale",
    type: "Condo",
    location: "Greenleaf, Chicago",
    price: 320000,
    bedrooms: 1,
    bathrooms: 1,
    size: 800,
    amenities: ["Gym", "Pet Friendly", "Balcony"],
    images: ["property-3-ext", "property-3-int-1"],
    agent: { name: "Emily White", avatar: "agent-3" },
    featured: false,
  },
  {
    id: "p4",
    title: "Vast Land for Development",
    description: "A large plot of land with excellent development potential. Zoned for residential or commercial use, this is a great investment opportunity.",
    status: "For Sale",
    type: "Land",
    location: "Oak Valley, Texas",
    price: 1200000,
    bedrooms: 0,
    bathrooms: 0,
    size: 435600, // 10 acres
    amenities: ["Zoned Residential", "Utilities Nearby"],
    images: ["property-4-ext"],
    agent: { name: "John Smith", avatar: "agent-2" },
    featured: false,
  },
  {
    id: "p5",
    title: "Charming Brick House",
    description: "A classic brick house with a beautiful garden and vintage details. This home combines traditional charm with modern comforts.",
    status: "For Sale",
    type: "House",
    location: "Rosewood, Boston",
    price: 890000,
    bedrooms: 5,
    bathrooms: 4,
    size: 3200,
    amenities: ["Garden", "Fireplace", "Hardwood Floors"],
    images: ["property-5-ext", "property-5-int-1"],
    agent: { name: "Jane Doe", avatar: "agent-1" },
    featured: true,
  },
  {
    id: "p6",
    title: "Sleek High-Rise Apartment",
    description: "Live above it all in this sleek, modern apartment on the 35th floor. Features floor-to-ceiling windows and panoramic city views.",
    status: "For Rent",
    type: "Apartment",
    location: "Skyview, Miami",
    price: 3800,
    bedrooms: 1,
    bathrooms: 1,
    size: 750,
    amenities: ["Pool", "Gym", "24h Security"],
    images: ["property-6-ext", "property-6-int-1"],
    agent: { name: "Emily White", avatar: "agent-3" },
    featured: true,
  },
  {
    id: "p7",
    title: "Sprawling Ranch with Acreage",
    description: "A beautiful ranch-style house on 5 acres of land. Perfect for those who love open spaces and privacy, with plenty of room for horses.",
    status: "For Sale",
    type: "House",
    location: "Sunset Hills, Austin",
    price: 1500000,
    bedrooms: 4,
    bathrooms: 4,
    size: 4000,
    amenities: ["Garage", "Garden", "Fireplace"],
    images: ["property-7-ext", "property-7-int-1"],
    agent: { name: "John Smith", avatar: "agent-2" },
    featured: false,
  },
  {
    id: "p8",
    title: "Modern Condo with Balcony",
    description: "A bright and airy modern condo in a recently built complex. Enjoy your morning coffee on the private balcony.",
    status: "For Sale",
    type: "Condo",
    location: "West End, Denver",
    price: 450000,
    bedrooms: 2,
    bathrooms: 2,
    size: 1100,
    amenities: ["Balcony", "Parking", "Gym"],
    images: ["property-8-ext", "property-8-int-1"],
    agent: { name: "Jane Doe", avatar: "agent-1" },
    featured: true,
  },
  {
    id: "p9",
    title: "Luxury Beachfront Villa",
    description: "An exquisite beachfront villa with direct access to a private beach. Wake up to the sound of waves in this slice of paradise.",
    status: "For Rent",
    type: "House",
    location: "Golden Beach, California",
    price: 15000,
    bedrooms: 5,
    bathrooms: 6,
    size: 5500,
    amenities: ["Pool", "Beach Access", "Ocean View", "Air Conditioning"],
    images: ["property-9-ext", "property-9-int-1"],
    agent: { name: "Emily White", avatar: "agent-3" },
    featured: true,
  },
  {
    id: "p10",
    title: "Rustic Cabin in the Woods",
    description: "Escape the city to this cozy and rustic cabin nestled in the forest. The perfect getaway for nature lovers, with hiking trails right outside your door.",
    status: "For Rent",
    type: "House",
    location: "Pine Ridge, Colorado",
    price: 2000,
    bedrooms: 3,
    bathrooms: 2,
    size: 1500,
    amenities: ["Fireplace", "Hiking Trails", "Pet Friendly"],
    images: ["property-10-ext", "property-10-int-1"],
    agent: { name: "John Smith", avatar: "agent-2" },
    featured: false,
  },
];

export const allAmenities: Amenity[] = [
    { id: 'Pool', label: 'Pool', icon: Waves },
    { id: 'Garage', label: 'Garage', icon: Car },
    { id: 'Garden', label: 'Garden', icon: Trees },
    { id: 'Air Conditioning', label: 'Air Conditioning', icon: Wind },
    { id: 'Gym', label: 'Gym', icon: Dumbbell },
    { id: 'Pet Friendly', label: 'Pet Friendly', icon: PawPrint },
    { id: 'Wifi', label: 'Wifi', icon: Wifi },
    { id: 'Furnished', label: 'Furnished', icon: Armchair },
    { id: 'Kitchen', label: 'Kitchen', icon: UtensilsCrossed },
];
